name: Upgit Formula Manager

on:
  workflow_call:
    outputs:
      needs_update:
        description: "Whether the formula needs update"
        value: ${{ jobs.manage.outputs.needs_update }}
      changes_summary:
        description: "Summary of changes made"
        value: ${{ jobs.manage.outputs.changes_summary }}
      new_version:
        description: "New version if updated"
        value: ${{ jobs.manage.outputs.new_version }}

jobs:
  manage:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.check.outputs.needs_update }}
      changes_summary: ${{ steps.update.outputs.changes_summary }}
      new_version: ${{ steps.check.outputs.latest_value }}
    steps:
      - name: Check for updates
        id: check
        uses: ./.github/workflows/shared/formula-checker.yml
        with:
          formula_name: "upgit"
          check_type: "github_release"
          repository: "pluveto/upgit"

      - name: Update formula
        id: update
        if: steps.check.outputs.needs_update == 'true'
        uses: ./.github/workflows/shared/formula-updater.yml
        with:
          formula_name: "upgit"
          update_data: ${{ steps.check.outputs.update_data }}
          update_type: "binary_checksums"
          binary_config: |
            {
              "platforms": ["macos_arm64", "macos_amd64", "linux_arm64", "linux_amd64"],
              "platform_configs": {
                "macos_arm64": {
                  "url_template": "https://github.com/pluveto/upgit/releases/download/v$VERSION/upgit_macos_arm64",
                  "filename": "upgit_macos_arm64",
                  "pattern": "if OS\\.mac\\?.*if Hardware::CPU\\.arm\\?"
                },
                "macos_amd64": {
                  "url_template": "https://github.com/pluveto/upgit/releases/download/v$VERSION/upgit_macos_amd64",
                  "filename": "upgit_macos_amd64",
                  "pattern": "if OS\\.mac\\?.*else"
                },
                "linux_arm64": {
                  "url_template": "https://github.com/pluveto/upgit/releases/download/v$VERSION/upgit_linux_arm64",
                  "filename": "upgit_linux_arm64",
                  "pattern": "elsif OS\\.linux\\?.*if Hardware::CPU\\.arm\\?"
                },
                "linux_amd64": {
                  "url_template": "https://github.com/pluveto/upgit/releases/download/v$VERSION/upgit_linux_amd64",
                  "filename": "upgit_linux_amd64",
                  "pattern": "elsif OS\\.linux\\?.*else"
                }
              }
            }
